//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollKurumsal {
    
    
    public partial class Arama {
        
        /// <summary>
        /// AramaKategoriKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.AramaKategoriKontrol AramaKategoriKontrol1;
        
        /// <summary>
        /// HaberGrubuUyeligiKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.HaberGrubuUyeligiKontrol HaberGrubuUyeligiKontrol1;
        
        /// <summary>
        /// BannerKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.BannerKontrol BannerKontrol1;
        
        /// <summary>
        /// AramaKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.AramaKontrol AramaKontrol1;
    }
}
