//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollKurumsal {
    
    
    public partial class Default {
        
        /// <summary>
        /// BaskanMenuKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.BaskanMenuKontrol BaskanMenuKontrol1;
        
        /// <summary>
        /// EtkinliklerKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.EtkinliklerKontrol EtkinliklerKontrol1;
        
        /// <summary>
        /// AnketKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.AnketKontrol AnketKontrol1;
        
        /// <summary>
        /// MansetSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.MansetSliderKontrol MansetSliderKontrol1;
        
        /// <summary>
        /// HaberlerMansetKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.HaberlerMansetKontrol HaberlerMansetKontrol1;
        
        /// <summary>
        /// DuyurularMansetKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.DuyurularMansetKontrol DuyurularMansetKontrol1;
        
        /// <summary>
        /// EtkinliklerMansetKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.EtkinliklerMansetKontrol EtkinliklerMansetKontrol1;
        
        /// <summary>
        /// IhalelerMansetKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.IhalelerMansetKontrol IhalelerMansetKontrol1;
        
        /// <summary>
        /// FotoGaleriSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.FotoGaleriSliderKontrol FotoGaleriSliderKontrol1;
        
        /// <summary>
        /// VideoGaleriSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.VideoGaleriSliderKontrol VideoGaleriSliderKontrol1;
        
        /// <summary>
        /// YayinlarGaleriSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.YayinlarGaleriSliderKontrol YayinlarGaleriSliderKontrol1;
        
        /// <summary>
        /// DokumanYayinlariGaleriSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.DokumanYayinlariGaleriSliderKontrol DokumanYayinlariGaleriSliderKontrol1;
        
        /// <summary>
        /// BannerSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.BannerSliderKontrol BannerSliderKontrol1;
        
        /// <summary>
        /// HizmetMenuKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.HizmetMenuKontrol HizmetMenuKontrol1;
        
        /// <summary>
        /// HizmetSliderKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.HizmetSliderKontrol HizmetSliderKontrol1;
        
        /// <summary>
        /// HaberGrubuUyeligiKontrol1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::EnrollKurumsal.UserKontroller.HaberGrubuUyeligiKontrol HaberGrubuUyeligiKontrol1;
    }
}
